"""
ZAP listing parser package (split by responsibility).

Re-exports the public surface previously provided by ``zap_listing_parser.py``.
"""

from ImoveisScrapy.spiders.utils.constants import (
    BASE_QUERY,
    BH_ONDE,
    BH_VIEWPORT,
    MAX_PAGES,
    TRANSACAO_ALUGUEL,
    TRANSACAO_VENDA,
    ZAP_AMENITY_LABELS,
)
from ImoveisScrapy.spiders.utils.geocoder import get_geo_from_address
from ImoveisScrapy.spiders.utils.html_extractors import (
    anchor_html_to_selector,
    get_aluguel,
    get_area,
    get_banheiros,
    get_condominio,
    get_detail_atualizado_ha,
    get_detail_bairro,
    get_detail_cidade,
    get_detail_endereco,
    get_detail_endereco_completo,
    get_detail_endereco_numero,
    get_detail_endereco_rua,
    get_detail_estado,
    get_detail_preco_aluguel_mensal,
    get_detail_preco_condominio_mensal,
    get_detail_preco_iptu_mensal,
    get_detail_preco_total_previsto_mensal,
    get_detail_publicado,
    get_detail_publicado_atualizado,
    get_iptu,
    get_property_data,
    get_vagas,
    parse_int_digits as parse_int,
)
from ImoveisScrapy.spiders.utils.json_extractors import (
    extract_amenities_from_listing,
    extract_json_data,
    get_aluguel_from_json,
    get_amenities_from_json,
    get_area_from_json,
    get_bairro_from_json,
    get_banheiros_from_json,
    get_bedrooms_from_json,
    get_cidade_from_json,
    get_condominio_from_json,
    get_detail_atualizado_ha_from_json,
    get_detail_publicado_ha_from_json,
    get_endereco_from_json,
    get_endereco_numero_from_json,
    get_endereco_rua_from_json,
    get_estado_from_json,
    get_external_id_from_json,
    get_fotos_from_json,
    get_geo_from_json,
    get_id_from_json,
    get_iptu_from_json,
    get_location_id_from_json,
    get_property_type_from_json,
    get_vagas_from_json,
    rental_pricing_info,
    zap_json_listing_bundle,
    zap_page_data_field,
)
from ImoveisScrapy.spiders.utils.models import (
    CasaMineiraItem,
    ImoveisScrapyItem,
    NetImoveisItem,
    QuintoAndarItem,
    VivaRealItem,
    ZapDetailPageMetadata,
    ZapMapViewport,
)
from ImoveisScrapy.spiders.utils.normalizers import (
    format_endereco_zap,
    nested_get as zap_nested_get,
    parse_first_int,
    value_is_absent as zap_value_is_absent,
)
from ImoveisScrapy.spiders.utils.parser import (
    extract_lat_lon_from_detail_html,
    getImvListFromPage,
    getImvQuantityFromListPage,
    parse_detail_page_metadata,
)
from ImoveisScrapy.spiders.utils.urls import BASE_PATH, page_url, urlRemoveParameters

extractJsonData = extract_json_data

__all__ = [
    "BASE_PATH",
    "BASE_QUERY",
    "BH_ONDE",
    "BH_VIEWPORT",
    "MAX_PAGES",
    "TRANSACAO_ALUGUEL",
    "TRANSACAO_VENDA",
    "ZAP_AMENITY_LABELS",
    "ZapDetailPageMetadata",
    "ZapMapViewport",
    "anchor_html_to_selector",
    "extractJsonData",
    "extract_amenities_from_listing",
    "extract_json_data",
    "extract_lat_lon_from_detail_html",
    "format_endereco_zap",
    "get_aluguel",
    "get_aluguel_from_json",
    "get_amenities_from_json",
    "get_area",
    "get_area_from_json",
    "get_bairro_from_json",
    "get_banheiros",
    "get_banheiros_from_json",
    "get_bedrooms_from_json",
    "get_cidade_from_json",
    "get_condominio",
    "get_condominio_from_json",
    "get_detail_atualizado_ha",
    "get_detail_atualizado_ha_from_json",
    "get_detail_bairro",
    "get_detail_cidade",
    "get_detail_endereco",
    "get_detail_endereco_completo",
    "get_detail_endereco_numero",
    "get_detail_endereco_rua",
    "get_detail_estado",
    "get_detail_preco_aluguel_mensal",
    "get_detail_preco_condominio_mensal",
    "get_detail_preco_iptu_mensal",
    "get_detail_preco_total_previsto_mensal",
    "get_detail_publicado",
    "get_detail_publicado_atualizado",
    "get_detail_publicado_ha_from_json",
    "get_endereco_from_json",
    "get_endereco_numero_from_json",
    "get_endereco_rua_from_json",
    "get_estado_from_json",
    "get_external_id_from_json",
    "get_fotos_from_json",
    "get_geo_from_address",
    "get_geo_from_json",
    "get_id_from_json",
    "get_iptu",
    "get_iptu_from_json",
    "get_location_id_from_json",
    "get_property_data",
    "get_property_type_from_json",
    "get_vagas",
    "get_vagas_from_json",
    "getImvListFromPage",
    "getImvQuantityFromListPage",
    "page_url",
    "parse_detail_page_metadata",
    "parse_first_int",
    "parse_int",
    "rental_pricing_info",
    "urlRemoveParameters",
    "zap_json_listing_bundle",
    "zap_nested_get",
    "zap_page_data_field",
    "zap_value_is_absent",
]
